let privit = 'hello';
console.log(privit);
alert(privit);
document.write(privit);
document.write('<br>');
let site = 'owu';
console.log(site);
alert(site);
document.write(site);
document.write('<br>');
let com = 'com';
console.log(com);
alert(com);
document.write(com);
document.write('<br>');
let ua = 'ua';
console.log(ua);
alert(ua);
document.write(ua);
document.write('<br>');
let number1 = 1;
console.log(number1);
alert(number1);
document.write(number1);
document.write('<br>');
let number2 = 10;
console.log(number2);
alert(number2);
document.write(number2);
document.write('<br>');
let number3 = -999;
console.log(number3);
alert(number3);
document.write(number3);
document.write('<br>');
let number4 = 123;
console.log(number4);
alert(number4);
document.write(number4);
document.write('<br>');
let number5 = 3.14;
console.log(number5);
alert(number5);
document.write(number5);
document.write('<br>');
let number6 = 2.7;
console.log(number6);
alert(number6);
document.write(number6);
document.write('<br>');
let number7 = 16;
console.log(number7);
alert(number7);
document.write(number7);
document.write('<br>');
let fal = false;
console.log(fal);
alert(fal);
document.write(fal);
document.write('<br>');
let tru = true;
console.log(tru);
alert(tru);
document.write(tru);
document.write('<br>');

privit = 'hi';
console.log(privit);
alert(privit);
document.write(privit);
document.write('<br>');
site = 'football';
console.log(site);
alert(site);
document.write(site);
document.write('<br>');
com = 'www';
console.log(com);
alert(com);
document.write(com);
document.write('<br>');
ua = 'pl';
console.log(ua);
alert(ua);
document.write(ua);
document.write('<br>');
number1 = 999;
console.log(number1);
alert(number1);
document.write(number1);
document.write('<br>');
number2 = 1000;
console.log(number2);
alert(number2);
document.write(number2);
document.write('<br>');
number3 = -111;
console.log(number3);
alert(number3);
document.write(number3);
document.write('<br>');
number4 = 444;
console.log(number4);
alert(number4);
document.write(number4);
document.write('<br>');
number5 = 6.66;
console.log(number5);
alert(number5);
document.write(number5);
document.write('<br>');
number6 = 9.9;
console.log(number6);
alert(number6);
document.write(number6);
document.write('<br>');
number7 = 88;
console.log(number7);
alert(number7);
document.write(number7);
document.write('<br>');
fal = true;
console.log(fal);
alert(fal);
document.write(fal);
document.write('<br>');
tru = false;
console.log(tru);
alert(tru);
document.write(tru);
document.write('<br>');

let constant1 = 3333;
console.log(constant1);
alert(constant1);
document.write(constant1);
document.write('<br>');
let constant2 = 4444;
console.log(constant2);
alert(constant2);
document.write(constant2);
document.write('<br>');
let constant3 = 5555;
console.log(constant3);
alert(constant3);
document.write(constant3);
document.write('<br>');
let text1 = 'andrey';
console.log(text1);
alert(text1);
document.write(text1);
document.write('<br>');
let text2 = 'cherevichnyi';
console.log(text2);
alert(text2);
document.write(text2);
document.write('<br>');
let text3 = 'viktorovich';
console.log(text3);
alert(text3);
document.write(text3);
document.write('<br>');
//
let name = prompt('enter your name')
console.log(name);
alert(name);
document.write(name);
document.write('<br>');
let surname = prompt('enter your surname')
console.log(surname);
alert(surname);
document.write(surname);
document.write('<br>');
let father = prompt('enter your father')
console.log(father);
alert(father);
document.write(father);
document.write('<br>');
let person=name+' '+surname+' '+father;
console.log(person);
alert(person);
document.write(person);
document.write('<br>');

let nameWife = prompt('enter your name')
console.log(nameWife);
alert(nameWife);
document.write(nameWife);
document.write('<br>');
let surnameWife = prompt('enter your surname')
console.log(surnameWife);
alert(surnameWife);
document.write(surnameWife);
document.write('<br>');
let fatherWife = prompt('enter your father')
console.log(fatherWife);
alert(fatherWife);
document.write(fatherWife);
document.write('<br>');
let personWife=fatherWife+' '+fatherWife+' '+fatherWife;
console.log(personWife);
alert(personWife);
document.write(personWife);
document.write('<br>');
let number10=prompt('enter number');
let number11=prompt('enter number');
let number12=prompt('enter number');
let number10numb=+number10;
let number11numb=+number11;
let number12numb=+number12;
console.log(number10numb, number11numb,number12numb, typeof number10numb,typeof number11numb, typeof number12numb  );
let num1=prompt('enter number');
let num2=prompt('enter number');
let num3=prompt('enter number');
let num4=prompt('enter number');
 let num1num=parseInt(num1);
let num2num=parseInt(num2);
let num3num=parseInt(num3);
let num4num=parseInt(num4);
let result1=num1num+num2num+num3num+num4num;
console.log(result1);

let num8=prompt('enter number');
let num9=prompt('enter number');
let num10=prompt('enter number');
let num8num=parseFloat(num8);
let num9num=parseFloat(num9);
let num10num=parseFloat(num10);
// let result1=num8num+num9num+num10num;
// console.log(result1);
let num12num=Math.round(num8num);
let num13num=Math.round(num9num);
let num14num=Math.round(num10num);
let result2=num12num+num13num+num14num;
console.log(result2 );

let a = 100;
let b = '100';
let c = true;
let d = undefined;
console.log(typeof a,typeof b, typeof c, typeof d );
console.log(5<6);
console.log(5>6);
console.log(5==6);
console.log(5>=6);
console.log(10==10);
console.log(10<=10);
console.log(10<10);
console.log(10>10);
console.log(10!=10);
console.log(123>123);
console.log(123==123);
